services:
  - type: web
    name: blogsphere
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn blog_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blogsphere-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: false

databases:
  - name: blogsphere-db
    plan: free
    databaseName: blogsphere
    user: blogsphere_user